### ISSUE TITLE
[Bug] Job will run as root

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-networkpolicy-canary#26]
The following error is logged

> Failed - Error: container has runAsNonRoot and image will run as root (pod: "batch-myjobxtrrkk4lt69-20240912125232-luh9gvpo-3j6yoxbr-6895s_radix-networkpolicy-canary-allowradix(49966bbb-a2d8-46c7-a084-75c004b89236)", container: myjob)

In Playground the job manager have issues
![image](https://github.com/user-attachments/assets/3fd80122-8125-4c4a-8594-9b88f6b7c528)

**Comment by nilsgstrabo** [comment]
Fixed with PR https://github.com/equinor/radix-networkpolicy-canary/pull/27
